version: '3'

services:
  portainer:
    image: portainer/portainer:1.23.0
    container_name: portainer-livraria
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
      - 8000:8000
